travis:
  secure:
    BINSTAR_TOKEN: hqgbaL+qkOYVugWFhcDeVfoabRL7hwA4jKw3I6Ov0UA/O6w2jgWoqsJWX6+KiSmDP1Lu8K+BJpXuBI6P6jvtPxYxOPAzoDCKsYoZGhZUT5E3vm6cUZfZZOO2xvuAa/MPUShvAfoj9OSSrvvyeywDIa+NZZH6e0IffTkpBRAu2jar+Wo/oJ0kVUXWtZkXIcKUOAiYsqxiYf9rgKKOqpj9LsOMVEw7fI7eqioCRbS3x1OnBAq+h0e96DhMHrINFByiqCOPKmx+ZDuvRRVGV5bstmoRpk38dnKzxWFOFkJ/QCZf60PQbwgZGHT9Oh8Kr2pswHC/v+n/zRqFNIChdjl0j2ItV/HdVMAWdErewef7WxjccSLQ6Bs/nBiWhBSEYNxZN05f58bOg6vv3qbAMS02nnAXYG/S/zVM2BjNUnnn5YNAEw7A3s1BZzPvwdoZTfaXm/oEnq9C5Vf/M0IEeRxAynpmT2M64Ur8+MigG/IU+Gsf7rXih2gC4jtu5TzMM15yNKlM0tnnW67JHvOUS0F/xLG0KlkWcB+eYhVSGZg7wwfFmn+3uSJscbRJH8ViNptLaLAFyt7Vr+JOnElUhOVUHvk/TYJGKsBbrqDfREG9rRk5JjVFAKCVPk+1CMGswmUNLxT+sxjCVZid9k0VzoL0lvhcv5Ezh2If5vCzCrV6q/A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
